function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 13-Nov-2019 04:57:05

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % N    = 10;   % Order
    % F3dB = 0.4;  % 3-dB Frequency
    %
    % h = fdesign.lowpass('n,f3db', N, F3dB);
    %
    % Hd = design(h, 'butter', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -0.53799252720361 0.740980389417787; 1 2 1 1 ...
        -0.431657123545375 0.396871794764859; 1 2 1 1 -0.369527377351241 ...
        0.195815712655833; 1 2 1 1 -0.334543036016498 0.0826040059485465; 1 2 1 ...
        1 -0.318681417484689 0.0312747301464421], ...
        'ScaleValues', [0.300746965553544; 0.241303667804871; ...
        0.206572083826148; 0.187015242483012; 0.178148328165438; 1]);
end

s = double(x);
y = step(Hd,s);

