function y = Hd5(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 13-Nov-2019 04:42:33

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 0.01;  % Passband Frequency
    % Fstop = 0.21;  % Stopband Frequency
    % Apass = 1;     % Passband Ripple (dB)
    % Astop = 80;    % Stopband Attenuation (dB)
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.94442388689775 0.948987809718331; 1 2 1 1 ...
        -1.87672829724071 0.881133325980336], ...
        'ScaleValues', [0.0011409807051444; 0.00110125718490659; 1]);
end

%s = double(x);
y = step(Hd,x);

